### PR TITLE
feat: added prefix filtering support

### LINKED ISSUE #176: Speed up searches for bin/paths
Perhaps an extra index could be built that only contains bin and sbin paths, and only allows full string search?

The problem is that nix-index is a lot slower than command-not-found: https://github.com/NixOS/nixpkgs/issues/39789#issuecomment-1000276113

for small systems, it would also be nice to /only/ have the binaries in the db, but that's a different issue I guess.

### PR DESCRIPTION
**Pull request by virchau13**
Added a way to only put paths starting with a certain prefix into the database, through a `--filter-prefix` flag. Should resolve #176, and is a way to solve NixOS/nixpkgs#39789.

```
--filter-prefix <PREFIX>    Only add paths starting with PREFIX (e.g. `/bin/`)
```

Some typos were also fixed.

### CODE REVIEW

**Comment by bennofs** [comment]
Thanks!

**Comment by wmertens** [comment]
Shouldn't this allow multiple paths? /bin and /sbin?

And this cannot be used to find .desktop files for something like a registry of all gui packages available, but maybe that would just use the entire index.

In any case, all those use cases could be covered with a regex match

**Comment by bennofs** [comment]
That's a good idea. I don't have much time right now to work on this but if anyone wants to replace the prefix filter by regex I am happy to review the changes.

**Comment by virchau13** [comment]
Yes... a regex match would probably be better. I implemented it this way mainly as a benchmark for nixpkgs#39789, and also because the change is so simple that it's hard to get wrong.

**Pull request merged**
