### PR TITLE
README: home-manager uses initExtra

### PR DESCRIPTION
**Pull request by wmertens**

### CODE REVIEW

**Comment by bennofs** [comment]
Thanks for the PR! The new version would be broken in `configuration.nix` though, right? So maybe we should keep both versions (perhaps leave one commented out with a message explaining it?)

**Comment by wmertens** [comment]
No idea actually, I only added it to home.nix

**Comment by equirosa** [comment]
I just checked, and yes, the NixOS configuration uses `programs.bash.interactiveShellInit`; so it'd be optimal to specify one for home-manager and another for NixOS, if that's ok :)

**Comment by bennofs** [comment]
I added a comment to the configuration in 9de4d51f5e744b3790a026c53cdccb8dbc10bbf1 for home-manager.

**Pull request closed without merging**
