### PR TITLE
chore: cleanup for a crate publish?

### PR DESCRIPTION
**Pull request by RaitoBezarius**
Hi there, thank you for the amazing piece of software.

I am using it intensively in my project with some local changes: https://github.com/RaitoBezarius/buildxyz — I would love to have it as a proper library dependency and upstream my stuff.

Are you interested into that?

### CODE REVIEW

**Comment by RaitoBezarius** [comment]
@bennofs Are you interested into sharing the developemnt of nix-index in nix-community?

**Comment by figsoda** [comment]
I would also be interested in joining the development, if that becomes a reality

**Comment by bennofs** [comment]
> @bennofs Are you interested into sharing the developemnt of nix-index in nix-community?

I think this is a good idea

**Comment by RaitoBezarius** [comment]
We can coordinate the transfer here: https://matrix.to/#/#nix-community:nixos.org and create a Nix Index team and you can decide to add us to it so we can be co-maintainers. :)

**Pull request merged**
